I, [2017-12-28 00:00:02#26136]  INFO -- : Daily devise interface
E, [2017-12-28 00:00:03#26136] ERROR -- : Get request(http://192.168.31.178:3000/spaces/get_devise_list?space_code=8a1isp)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/raspi_net/remote_server/base/devise.rb:9:in `check_devise_state'", "/home/pi/workspace/remote_server/devise.rb:19:in `initialize'", "/home/pi/workspace/remote_server/devise.rb:24:in `new'", "/home/pi/workspace/remote_server/devise.rb:24:in `<main>'"]
E, [2017-12-28 00:00:03#26133] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:01:02#26150] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:02:03#26160] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:03:03#26170] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:04:02#26180] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:05:04#26190] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:06:06#26201] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:07:03#26211] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:08:02#26222] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:09:03#26232] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:10:03#26242] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:11:02#26253] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:12:03#26263] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:13:03#26273] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:14:02#26283] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:15:03#26295] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:16:03#26305] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:17:03#26321] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:18:02#26342] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:19:03#26353] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:20:03#26363] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:21:02#26374] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:22:03#26390] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:23:03#26400] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:24:02#26411] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:25:03#26421] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:26:03#26431] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:27:02#26441] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:28:03#26452] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:29:03#26462] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:30:02#26472] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:31:02#26482] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:32:03#26493] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:33:03#26503] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:34:02#26514] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:35:03#26524] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:36:03#26534] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:37:02#26544] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:38:03#26555] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:39:03#26565] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:40:02#26576] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:41:02#26586] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:42:03#26596] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:43:03#26606] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:44:02#26616] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:45:03#26626] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:46:03#26637] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:47:02#26648] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:48:03#26661] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:49:03#26671] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:50:02#26681] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:51:03#26691] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:52:03#26701] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:53:02#26712] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:54:03#26723] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:55:03#26733] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:56:02#26743] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:57:04#26753] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:58:04#26764] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 00:59:02#26775] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
I, [2017-12-28 01:00:03#26791]  INFO -- : Daily devise interface
E, [2017-12-28 01:00:03#26791] ERROR -- : Get request(http://192.168.31.178:3000/spaces/get_devise_list?space_code=8a1isp)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/raspi_net/remote_server/base/devise.rb:9:in `check_devise_state'", "/home/pi/workspace/remote_server/devise.rb:19:in `initialize'", "/home/pi/workspace/remote_server/devise.rb:24:in `new'", "/home/pi/workspace/remote_server/devise.rb:24:in `<main>'"]
E, [2017-12-28 01:00:03#26793] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:01:03#26807] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:02:02#26817] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:03:02#26827] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:04:03#26837] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:05:02#26847] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:06:02#26858] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:07:03#26870] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:08:03#26880] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:09:02#26890] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:10:03#26900] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:11:03#26910] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:12:02#26921] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:13:03#26933] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:14:03#26943] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:15:02#26953] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:16:03#26964] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:17:03#26982] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:18:02#27001] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:19:03#27012] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:20:06#27022] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:21:03#27032] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:22:03#27047] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:23:06#27058] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:24:03#27069] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:25:03#27079] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:26:03#27089] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:27:03#27099] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:28:02#27110] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:29:03#27120] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:30:03#27130] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:31:03#27140] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:32:02#27150] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:33:03#27161] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:34:03#27171] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:35:02#27182] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:36:03#27192] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:37:03#27202] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:38:03#27212] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:39:02#27222] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:40:03#27234] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:41:03#27244] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:42:10#27255] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:43:02#27265] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:Connection refused - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:44:21#27275] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:45:05#27286] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:46:05#27296] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:47:06#27306] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:48:05#27317] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:49:06#27327] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:50:06#27337] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:51:05#27347] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:52:06#27358] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:53:06#27368] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:54:05#27379] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:55:06#27389] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:56:06#27399] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:57:05#27409] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:58:06#27422] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
E, [2017-12-28 01:59:06#27432] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
I, [2017-12-28 02:00:02#27448]  INFO -- : Daily devise interface
E, [2017-12-28 02:00:05#27448] ERROR -- : Get request(http://192.168.31.178:3000/spaces/get_devise_list?space_code=8a1isp)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/raspi_net/remote_server/base/devise.rb:9:in `check_devise_state'", "/home/pi/workspace/remote_server/devise.rb:19:in `initialize'", "/home/pi/workspace/remote_server/devise.rb:24:in `new'", "/home/pi/workspace/remote_server/devise.rb:24:in `<main>'"]
E, [2017-12-28 02:00:05#27450] ERROR -- : Get request(http://192.168.31.178:3000/spaces/hartbit?space_code=8a1isp&cron=1513864806&cmd_quota=1512803265)Error:No route to host - connect(2) for "192.168.31.178" port 3000 at:["/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:583:in `start'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:478:in `get_response'", "/home/pi/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:455:in `get'", "/home/pi/workspace/raspi_net/remote_server/base/http.rb:25:in `_get'", "/home/pi/workspace/remote_server/hartbit.rb:25:in `send_hartbit'", "/home/pi/workspace/remote_server/hartbit.rb:37:in `<main>'"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   